export default {
    'no-unused-vars': 'warn',
    semi: ['warn', 'never'],
    quotes: ['warn', 'single', { avoidEscape: true }],
    'array-callback-return': 'warn',
    'no-await-in-loop': 'warn',
    'no-constructor-return': 'warn',
    'no-debugger': 'warn',
    'no-promise-executor-return': 'error',
    'no-self-compare': 'error',
    'no-sparse-arrays': 'error',
    'no-use-before-define': ['error', {
        functions: false,
        classes: true,
        variables: true,
        allowNamedExports: true
    }],
    'require-atomic-updates': 'warn',
    'accessor-pairs': 'warn',
    // camelcase: ['warn', { ignoreDestructuring: true }],
    'capitalized-comments': 'off',
    'consistent-this': ['warn', 'that'],
    'default-case-last': 'error',
    'default-param-last': 'warn',
    'dot-notation': 'warn',
    eqeqeq: 'warn',
    'grouped-accessor-pairs': ['warn', 'getBeforeSet'],
    'init-declarations': ['warn'],
    'max-depth': ['error', { max: 3 }],
    'max-lines-per-function': 'off',
    'max-nested-callbacks': ['error', 3],
    'max-params': ['error', 3],
    'no-alert': 'error',
    'no-bitwise': 'warn',
    'no-console': ['error', { allow: ['error', 'warn'] }],
    'no-continue': 'off',
    'no-delete-var': 'error',
    'no-else-return': 'error',
    'no-empty-function': 'warn',
    'no-extra-bind': 'warn',
    'no-extra-boolean-cast': 'warn',
    'no-lone-blocks': 'warn',
    'no-loop-func': 'warn',
    'no-multi-assign': 'error',
    'no-multi-str': 'error',
    'no-nested-ternary': 'error',
    'no-new': 'off',
    'no-unneeded-ternary': 'error',
    'no-useless-constructor': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'prefer-destructuring': ['warn', { object: true, array: false }],
    'prefer-object-spread': 'warn',
    'prefer-template': 'warn',
    'require-await': 'warn',
    'array-bracket-spacing': ['error', 'never'],
    'array-element-newline': ['error', 'consistent'],
    'arrow-parens': ['error', 'always'],
    'arrow-spacing': ['error', { 
        before: true, 
        after: true 
    }],
    'block-spacing': ['error', 'always'],
    'brace-style': ['error', '1tbs', { 
        allowSingleLine: true
    }],
    'comma-dangle': ['error', 'never'],
    'comma-spacing': ['error', { 
        before: false, 
        after: true
    }],
    'comma-style': ['error', 'last'],
    'dot-location': ['error', 'property'],
    'func-call-spacing': ['error', 'never'],
    'function-call-argument-newline': ['error', 'consistent'],
    'implicit-arrow-linebreak': ['error', 'beside'],
    indent: ['error', 4],
    'key-spacing': ['error', { afterColon: true }],
    'keyword-spacing': ['error', { after: true }],
    'lines-between-class-members': ['error', 'always'],
    'max-statements-per-line': ['error', { max: 1 }],
    'multiline-ternary': ['error', 'always-multiline'],
    'new-parens': 'error',
    'no-confusing-arrow': ['error', { onlyOneSimpleParam: true }],
    'no-extra-parens': 'error',
    'no-floating-decimal': 'error',
    'no-multi-spaces': 'error',
    'no-multiple-empty-lines': ['error', { max: 1 }],
    'no-whitespace-before-property': 'warn',
    'object-curly-spacing': ['error', 'always'],
    'one-var-declaration-per-line': ['error', 'always'],
    'quote-props': ['error', 'as-needed'],
    'space-before-blocks': ['error', 'always'],
    'space-before-function-paren': ['error', {
        anonymous: 'always',
        named: 'never',
        asyncArrow: 'always'
    }],
    'space-in-parens': ['error', 'never'],
    'space-infix-ops': 'error',
    'template-curly-spacing': ['error', 'always']
}